backend:
  name: github
  repo: Fatihcloud/HL-Deneme
  branch: main

media_folder: "static/img" # Medya dosyaları için saklama klasörü
public_folder: "/img" # Medya dosyalarının URL erişim yolu

collections:
  - name: blog
    label: "Blog"
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Dosya adı formatı
    fields:
      - { name: title, label: "Title", widget: "string" }
      - { name: slug, label: "Slug", widget: "string" }
      - { name: body, label: "Body", widget: "markdown" }
