backend:
  name: git-gateway
  repo: Fatihcloud/HL-Deneme # GitHub depo adı
  branch: main # Git üzerinde kullanılacak dal (örneğin: main)

media_folder: static/img # Yüklenen dosyaların kaydedileceği yer
public_folder: /img # Yüklenen dosyaların URL üzerinden erişimi

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
