backend:
  name: git-gateway
  branch: main

media_folder: static/img # Medya dosyalarının saklanacağı klasör
public_folder: /img # Medya dosyalarının URL erişimi

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
