backend:
  name: github
  repo: Fatihcloud/HL-Deneme # GitHub repo adı
  branch: main

media_folder: "static/img" # Medya dosyalarının kaydedileceği klasör
public_folder: "/img" # Medya dosyalarının URL erişim yolu

collections:
  # Blog gönderileri
  - name: blog
    label: "Blog"
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Dosya adı formatı
    fields:
      - { name: title, label: "Title", widget: "string" }
      - { name: slug, label: "Slug", widget: "string" }
      - { name: body, label: "Body", widget: "markdown" }

  # Ana Documentation Koleksiyonu
  - name: docs
    label: "Documentation"
    folder: docs # Ana doküman klasörü
    create: true
    slug: "{{slug}}" # Basit dosya adı formatı
    fields:
      - { name: id, label: "ID", widget: "string", required: true }
      - { name: title, label: "Title", widget: "string" }
      - { name: body, label: "Body", widget: "markdown" }

  # Alt klasörler için ayrı koleksiyonlar
  - name: tutorial_basics
    label: "Tutorial Basics"
    folder: docs/tutorial-basics
    create: true
    slug: "{{slug}}"
    fields:
      - { name: id, label: "ID", widget: "string", required: true }
      - { name: title, label: "Title", widget: "string" }
      - { name: body, label: "Body", widget: "markdown" }

  # - name: tutorial_extras
  #   label: "Tutorial Extras"
  #   folder: docs/tutorial-extras
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { name: id, label: "ID", widget: "string", required: true }
  #     - { name: title, label: "Title", widget: "string" }
  #     - { name: body, label: "Body", widget: "markdown" }
